# Generated by Django 3.1.2 on 2020-12-08 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_time_hosted',
            field=models.DateTimeField(default=datetime.date(2019, 4, 13), verbose_name='last_time_hosted'),
        ),
    ]
