# Generated by Django 3.1.2 on 2020-12-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
