# Generated by Django 3.1.2 on 2020-12-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_last_time_hosted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_time_hosted',
            field=models.DateTimeField(blank=True, verbose_name='last_time_hosted'),
        ),
    ]
