# Generated by Django 3.1.2 on 2020-12-08 14:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn', models.IntegerField(default=0)),
                ('board', models.CharField(max_length=5000)),
                ('last_move', models.DateTimeField(auto_now_add=True, verbose_name='last_move')),
                ('score_1', models.IntegerField(default=0)),
                ('score_2', models.IntegerField(default=0)),
                ('score_3', models.IntegerField(default=None, null=True)),
                ('score_4', models.IntegerField(default=None, null=True)),
                ('bag', models.CharField(default=None, max_length=200)),
                ('letters1', models.CharField(default=None, max_length=20)),
                ('letters2', models.CharField(default=None, max_length=20)),
                ('letters3', models.CharField(default=None, max_length=20, null=True)),
                ('letters4', models.CharField(default=None, max_length=20, null=True)),
                ('move1', models.CharField(default=None, max_length=7, null=True)),
                ('move2', models.CharField(default=None, max_length=7, null=True)),
                ('move3', models.CharField(default=None, max_length=7, null=True)),
                ('move4', models.CharField(default=None, max_length=7, null=True)),
                ('client1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client1_game', to=settings.AUTH_USER_MODEL)),
                ('client2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client2_game', to=settings.AUTH_USER_MODEL)),
                ('client3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client3_game', to=settings.AUTH_USER_MODEL)),
                ('client4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client4_game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=49)),
                ('game_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('move', models.CharField(max_length=100)),
                ('is_game_ended', models.BooleanField(default=False)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testing.gamestate')),
            ],
        ),
        migrations.CreateModel(
            name='Matchmaking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_players', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('client1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client1_match', to=settings.AUTH_USER_MODEL)),
                ('client2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client2_match', to=settings.AUTH_USER_MODEL)),
                ('client3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client3_match', to=settings.AUTH_USER_MODEL)),
                ('client4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client4_match', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
