# Generated by Django 3.1.2 on 2020-12-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='start_time'),
        ),
    ]
