# Generated by Django 3.1.2 on 2020-12-08 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='start_time',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='last_move',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 8, 14, 20, 46, 164908, tzinfo=utc), verbose_name='last_move'),
            preserve_default=False,
        ),
    ]
