# Generated by Django 3.1.4 on 2020-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='move1',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='move2',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='move3',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='move4',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
