# Generated by Django 3.1.2 on 2020-12-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='bag',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='letters1',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='letters2',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='letters3',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='letters4',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
