# Generated by Django 3.1.2 on 2020-12-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20201208_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='last_move',
            field=models.DateTimeField(default=1607440881.7886808, verbose_name='last_move'),
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.gamestate'),
        ),
    ]
