# Generated by Django 3.1.3 on 2020-12-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_gamestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='turn',
            field=models.CharField(default='game_not_started', max_length=20),
        ),
    ]
