# Generated by Django 3.1.4 on 2020-12-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20201205_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='move3',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='move4',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
    ]
