# Generated by Django 3.1.3 on 2020-12-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20201202_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='value',
            new_name='game_id',
        ),
    ]
