# Generated by Django 3.1.4 on 2020-12-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20201205_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='move1',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='move2',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
    ]
