# Generated by Django 3.1.2 on 2020-12-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20201208_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='last_move',
            field=models.DateTimeField(default=1607442456.1670809, verbose_name='last_move'),
        ),
    ]
