# Generated by Django 3.1.4 on 2020-12-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20201205_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=7)),
                ('game_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
