# Generated by Django 3.1.3 on 2020-12-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20201202_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchmaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='gamestate',
            name='client_id1',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestate',
            name='client_id2',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestate',
            name='username1',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestate',
            name='username2',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='game_id',
            field=models.CharField(max_length=20),
        ),
    ]
