# Generated by Django 3.1.2 on 2020-12-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20201208_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='last_move',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last_move'),
        ),
    ]
