# Generated by Django 3.1.4 on 2020-12-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20201202_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='score_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='score_2',
            field=models.IntegerField(default=0),
        ),
    ]
