# Generated by Django 3.1.2 on 2020-12-08 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20201208_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 8, 21, 41, 10, 167537, tzinfo=utc), verbose_name='created_date'),
            preserve_default=False,
        ),
    ]
