# Generated by Django 3.1.4 on 2020-12-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_merge_20201206_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
